# 서버 포트 설정
server:
  port: 8090

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/translate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_taba
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

# Flask 서버 URL 설정
flask:
  server:
    url: http://127.0.0.1:5000
  auth:
    token: myToken1234

# Frontend 서버 URL 설정
### 없어도 될 것 같음
frontend:
  server:
    url: http://localhost:3000

image:
  upload:
    dir: C:/Users/idyll
  base:
    url: http://192.168.0.37:8090/uploads

